name: CI

# run on all branches
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  run-base-tests:
    runs-on: ubuntu-latest
    strategy:
      # it's helpful to see exactly which test modules passed/failed
      # this finishes all matrix nodes even if one fails along the way
      fail-fast: false

      # all combinations that we will run in parallel to increase throughput
      matrix:
        include:

          - scala-version: "2.12.14"
            BUILD: "debug -- classpath issues locally"
            TEST_TARGET: ""
            script: './sbt testOnly com.twitter.scalding.reducer_estimation.ReducerEstimatorTest'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TARGET: "scalding-args scalding-date maple scalding-quotation"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TAGET: "scalding-avro scalding-hraven scalding-commons scalding-parquet scalding-parquet-scrooge"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TARGET: "scalding-core scalding-jdbc scalding-json scalding-db scalding-cats"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TARGET: "scalding-hadoop-test"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TARGET: "scalding-estimators-test"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TARGET: "scalding-serialization scalding-spark scalding-beam"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "base"
            TEST_TARGET: "scalding-thrift-macros"
            script: './scripts/run_test.sh'

          - scala-version: "2.12.14"
            BUILD: "test tutorials and matrix tutorials and repl"
            script: "./scripts/run_test.sh && ./scripts/build_assembly_no_test.sh scalding-assembly && ./scripts/test_tutorials.sh && ./scripts/build_assembly_no_test.sh scalding-assembly && ./scripts/test_matrix_tutorials.sh"

          - scala-version: "2.12.14"
            BUILD: "test repl and typed tutorials and microsite"
            script: "./sbt ++$TRAVIS_SCALA_VERSION clean docs/makeMicrosite && ./scripts/build_assembly_no_test.sh scalding-repl && ./scripts/test_repl_tutorial.sh && ./scripts/build_assembly_no_test.sh scalding-core && ./scripts/test_typed_tutorials.sh && ./scripts/build_assembly_no_test.sh execution-tutorial && ./scripts/test_execution_tutorial.sh"


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: 8

      - uses: coursier/cache-action@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4

      - name: Install Ruby Gems
        run: |
          gem install sass -v 3.7.4
          gem install jekyll -v 3.2.1

      # this is temporary until cascading releases an official 4.5 artifact
      # wip-4.5 is the first tag with a hadoop3 target
      - name: "Compile experimental cascading WIP"
        run: |
          cd experimental-cascading
          ./build-cascading.sh
          ls -R /home/runner/.m2/

      - name: "Run Test Variant"
        env:
          TRAVIS_SCALA_VERSION: ${{ matrix.scala-version }}
          BUILD: ${{ matrix.BUILD }}
          TEST_TARGET: ${{ matrix.TEST_TARGET }}

        run: |
          mkdir -p /home/runner/.ivy2/cache/ # some scripts assume that this folder exists
          ${{ matrix.script }}
