name: CI

on:
  pull_request:
    branches:
      - develop
      - master
      - main
  push:
    branches:
      - add_github_ci

jobs:
  run-base-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [ 2.11.12, 2.12.14 ]
        include:

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && TEST_TARGET="scalding-args scalding-date maple scalding-quotation"'

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && export TEST_TARGET="scalding-avro scalding-hraven scalding-commons scalding-parquet scalding-parquet-scrooge"'

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && export TEST_TARGET="scalding-core scalding-jdbc scalding-json scalding-db scalding-cats"'

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && export TEST_TARGET="scalding-hadoop-test"'

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && export TEST_TARGET="scalding-estimators-test"'

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && export TEST_TARGET="scalding-serialization scalding-spark"'

          - script: './scripts/run_test.sh'
            env: 'export BUILD="base" && TEST_TARGET="scalding-thrift-macros"'

          - script: './scripts/run_test.sh && ./scripts/build_assembly_no_test.sh scalding-assembly && ./scripts/test_tutorials.sh && ./scripts/build_assembly_no_test.sh scalding-assembly && ./scripts/test_matrix_tutorials.sh'
            env: 'export BUILD="test tutorials and matrix tutorials and repl"'

          - script: './sbt ++$TRAVIS_SCALA_VERSION clean docs/makeMicrosite && ./scripts/build_assembly_no_test.sh scalding-repl && ./scripts/test_repl_tutorial.sh && ./scripts/build_assembly_no_test.sh scalding-core && ./scripts/test_typed_tutorials.sh && ./scripts/build_assembly_no_test.sh execution-tutorial && ./scripts/test_execution_tutorial.sh'
            env: 'export BUILD="test repl and typed tutorials and microsit"'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: 8

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4

      - name: Install Ruby Gems
        run: |
          gem install sass -v 3.7.4
          gem install jekyll -v 3.2.1

      - name: Install APT Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install md5deep -y

      - name: "Run Test Variant"
        env:
          TRAVIS_SCALA_VERSION: "${{ matrix.scala-version }}"
        run: |
          "${{ matrix.env }} && ${{ matrix.script }}"
